services:
  db:
    image: postgis/postgis
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - "./infra/pgadmin/servers.json:/pgadmin4/servers.json"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: geheim
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - app-network
  ors-app:
    container_name: ors-app
    image: openrouteservice/openrouteservice:v9.0.0
    ports:
      - "8080:8082"
      - "9001:9001"
    user: "1000:1000" # Default is 1000:1000. make infra/up will override this to the actual user values
    volumes:
      - ./infra/ors:/home/ors
    environment:
      ors.engine.profile_default.build.source_file: /home/ors/files/sh.osm.pbf
      REBUILD_GRAPHS: false
      CONTAINER_LOG_LAVEL: INFO
      XMS: 1g
      XMX: 2g
      ADDITIONAL_JAVA_OPTS: ""
    networks:
      - app-network
  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    ports:
      - 2525:3000
    volumes:
      - ./infra/vroom:/conf
    environment:
      VROOM_ROUTER: ors
    networks:
      - app-network
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./infra/valhalla/custom_files:/custom_files
networks:
  app-network:
    driver: bridge
